[package]

name = "rust-bindgen"
version = "0.13.0"
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
license = "BSD-3-Clause"

build = "build.rs"

[lib]

name = "bindgen"
path = "src/lib.rs"
plugin = true

[dependencies]

regex = "*"

[[bin]]

name = "bindgen"
doc = false

[[test]]
name = "tests"
